import{i as h,S,a as w}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const g={form:document.querySelector("#request-form"),gallery:document.querySelector(".gallery"),loadBtn:document.querySelector(".load-btn")},n={info:"Please enter a value in the search field!",endOfSearch:"We're sorry, but you've reached the end of search results.",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there are no connection to the server. Please try again later!",exception:"Exception: We have some issue with connection. Please try again later!"},a={blue:"#abd4f8",orange:"#f28111",red:"#e97782"},m={click:"click",submit:"submit"};function i(e,t){h.info({position:"topRight",backgroundColor:`${t}`,message:`${e}`})}const E=new S(".gallery a",{captionsData:"alt",captionDelay:250}),{gallery:v}=g;function O(e){v.insertAdjacentHTML("beforeend",$(e)),E.refresh()}function $(e){return e.hits.map(({webformatURL:t,largeImageURL:r,tags:c,likes:o,views:s,comments:l,downloads:L})=>`<li>
                <a href="${r}"><img src='${t}' alt='${c}' loading="lazy" ></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${o}</p></div>
                    <div class="item"><h3>Views</h3><p>${s}</p></div>
                    <div class="item"><h3>Comments</h3><p>${l}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${L}</p></div>
                </div>
            </li>`).join("")}function R(){v.insertAdjacentHTML("beforeend",`<div class='loader-wrapper'>
        <div class='loader'></div>
    </div>`)}const q="44405804-89924783490777dc17a96fec8",x="https://pixabay.com/api/?",f={params:{key:q,image_type:"photo",orientations:"horizontal",safesearch:!0,page:1,per_page:15}};async function P(e,t){R();try{return f.params.q=e,f.params.page=t,(await w.get(x,f)).data}catch(r){if(r.response){const{data:c}=r.response;i(`${n.exception} ERROR: ${c}`,a.orange)}else r.request?i(`${n.exception} ERROR: ${r.request}`,a.orange):i(`${n.exception} ERROR: ${r.message}`,a.orange)}}const{form:G,gallery:M,loadBtn:d}=g;let p="",u=1,y="";const A=15;G.addEventListener("submit",async e=>{e.preventDefault(),d.classList.remove("visible"),M.innerHTML="",u=1;const t=e.target.search.value.trim();if(y=m.submit,h.destroy(),p=t,!t){i(n.info,a.blue);return}try{await b(p,u)}catch(r){console.log("submit",r),i(n.exception+r,a.orange)}e.target.reset()});d.addEventListener("click",async()=>{y=m.click,d.classList.remove("visible");try{await b(p,u);const e=document.querySelector("li"),{height:t}=e.getBoundingClientRect();_(t*3,0)}catch(e){console.log("click",e),i(n.exception+e,a.orange)}});async function b(e,t){y===m.click&&(t+=1,u=t);try{const r=await P(e,t);if(I(r)){const c=Math.round(r.totalHits/t);O(r),B(c)}}catch(r){console.log("renderGallery",r),i(n.exception+r,a.orange)}T()}function _(e=0,t=0){window.scrollBy({top:e,left:t,behavior:"smooth"})}function T(){document.querySelector(".loader-wrapper").remove()}function I(e){return e?e.totalHits===0?(i(n.warning,a.red),!1):!0:!1}function B(e){if(e<=A){d.classList.remove("visible"),i(n.endOfSearch,a.blue);return}d.classList.add("visible")}
//# sourceMappingURL=commonHelpers.js.map
